# Generated by Django 3.1 on 2020-08-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'All department'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Nombre corto'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
